/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_themaister_glfft_Native */

#ifndef _Included_net_themaister_glfft_Native
#define _Included_net_themaister_glfft_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_themaister_glfft_Native
 * Method:    runTestSuite
 * Signature: ()V
 */
JNIEXPORT jint JNICALL Java_net_themaister_glfft_Native_runTestSuite
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
