/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_themaister_glfft_Native */

#ifndef _Included_net_themaister_glfft_Native
#define _Included_net_themaister_glfft_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_themaister_glfft_Native
 * Method:    beginRunTestSuiteTask
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_themaister_glfft_Native_beginRunTestSuiteTask
  (JNIEnv *, jclass);

/*
 * Class:     net_themaister_glfft_Native
 * Method:    beginBenchTask
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_themaister_glfft_Native_beginBenchTask
  (JNIEnv *, jclass);

/*
 * Class:     net_themaister_glfft_Native
 * Method:    endTask
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_themaister_glfft_Native_endTask
  (JNIEnv *, jclass);

/*
 * Class:     net_themaister_glfft_Native
 * Method:    isComplete
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_themaister_glfft_Native_isComplete
  (JNIEnv *, jclass);

/*
 * Class:     net_themaister_glfft_Native
 * Method:    getExitCode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_themaister_glfft_Native_getExitCode
  (JNIEnv *, jclass);

/*
 * Class:     net_themaister_glfft_Native
 * Method:    pull
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_themaister_glfft_Native_pull
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
