#!/bin/sh

# It is assumed that paths do not have spaces, as it's only used internally.

INPUT=$1
OUTPUT=$2
INPUT_NO_EXT=`echo $INPUT | sed -e 's/.comp$//'`
INPUT_NO_EXT=`basename $INPUT_NO_EXT`

echo "// This file is autogenerated by shader_to_inc.sh." > $OUTPUT
echo "#ifndef ${INPUT_NO_EXT}_inc__" >> $OUTPUT
echo "#define ${INPUT_NO_EXT}_inc__" >> $OUTPUT
echo "namespace GLFFT { namespace Blob {" >> $OUTPUT
echo "static const char ${INPUT_NO_EXT}_source[] = R\"DELIM(" >> $OUTPUT
cat $INPUT >> $OUTPUT
echo ")DELIM\";" >> $OUTPUT
echo "}}" >> $OUTPUT
echo "#endif" >> $OUTPUT
